# Generated by Django 4.1 on 2023-05-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gambar',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
