# Generated by Django 4.1 on 2023-05-27 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_alamat_userprofile_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default=datetime.datetime(2023, 5, 27, 16, 4, 28, 966131, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
