# Generated by Django 4.1 on 2023-05-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
