# Generated by Django 4.1 on 2023-06-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tugas_dosen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugas',
            name='dosen',
        ),
    ]
