# Generated by Django 4.1 on 2023-06-29 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_tugas_dosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='tanggal_dibuat',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 15, 9, 12, 253119, tzinfo=datetime.timezone.utc)),
        ),
    ]
