# Generated by Django 4.1 on 2023-06-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_tugas_tanggal_dibuat'),
    ]

    operations = [
    ]
