# Generated by Django 4.0.7 on 2023-07-01 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jurusan',
            field=models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Farmasi', 'Farmasi')], default=datetime.datetime(2023, 7, 1, 3, 31, 22, 920296, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4'), ('semester5', 'Semester 5'), ('semester6', 'Semester 6'), ('semester7', 'Semester 7'), ('semester8', 'Semester 8')], default=datetime.datetime(2023, 7, 1, 3, 31, 32, 413555, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
