# Generated by Django 4.1 on 2023-06-29 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tugas_nama_pengguna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='nama_pengguna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile'),
        ),
    ]
