# Generated by Django 4.1 on 2023-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_jurusan_userprofile_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.DateTimeField(),
        ),
    ]
