# Generated by Django 4.1 on 2023-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tugas_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='semester',
            field=models.CharField(choices=[('Semester1', 'Semester 1'), ('Semester2', 'Semester 2'), ('Semester3', 'Semester 3'), ('Semester4', 'Semester 4'), ('Semester5', 'Semester 5'), ('Semester6', 'Semester 6'), ('Semester7', 'Semester 7'), ('Semester8', 'Semester 8')], max_length=20),
        ),
    ]
