# Generated by Django 4.1.9 on 2023-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tugas_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('tugas', 'Tugas'), ('materi', 'Materi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gambar',
            field=models.ImageField(upload_to='profile_images/'),
        ),
    ]
