# Generated by Django 4.1 on 2023-05-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveIntegerField()),
                ('jurusan', models.CharField(max_length=100)),
                ('day', models.CharField(choices=[('Monday', 'Senin'), ('Tuesday', 'Selasa'), ('Wednesday', 'Rabu'), ('Thursday', 'Kamis'), ('Friday', 'Jumat'), ('Saturday', 'Sabtu'), ('Sunday', 'Minggu')], max_length=10)),
                ('time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('sks', models.PositiveIntegerField()),
                ('learning_method', models.CharField(choices=[('Online', 'Daring'), ('Offline', 'Luring')], max_length=10)),
                ('lecturer', models.CharField(max_length=100)),
            ],
        ),
    ]
