# Generated by Django 4.1 on 2023-05-29 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10)),
                ('waktu', models.CharField(max_length=20)),
                ('kode_mata_kuliah', models.CharField(max_length=20)),
                ('nama_mata_kuliah', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
                ('jurusan', models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Farmasi', 'Farmasi')], max_length=50)),
                ('semester', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4'), ('semester5', 'Semester 5'), ('semester6', 'Semester 6'), ('semester7', 'Semester 7'), ('semester8', 'Semester 8')], max_length=20)),
                ('ruangan', models.CharField(max_length=50)),
                ('metode_pembelajaran', models.CharField(choices=[('luring', 'Luring'), ('daring', 'Daring')], max_length=10)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
