# Generated by Django 4.1 on 2023-07-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tugas_pengirim_tugas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tugas',
            name='pengirim_tugas',
        ),
        migrations.AlterField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('materi', 'Materi'), ('tugas', 'Tugas')], max_length=50),
        ),
    ]
