# Generated by Django 4.1 on 2023-06-24 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tugas_alter_jadwal_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='jurusan',
            field=models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Farmasi', 'Farmasi')], default=datetime.datetime(2023, 6, 24, 8, 28, 27, 521619, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tugas',
            name='semester',
            field=models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4'), ('semester5', 'Semester 5'), ('semester6', 'Semester 6'), ('semester7', 'Semester 7'), ('semester8', 'Semester 8')], default=datetime.datetime(2023, 6, 24, 8, 28, 42, 22719, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
    ]
