# Generated by Django 4.1 on 2023-06-29 16:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('dosen', 'Dosen'), ('admin', 'Admin')], max_length=10)),
                ('nim_nidn', models.CharField(max_length=20)),
                ('gambar', models.ImageField(blank=True, upload_to='profile_images/')),
                ('alamat', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tugas', models.CharField(max_length=100)),
                ('tanggal_dibuat', models.DateTimeField(default=datetime.datetime.now)),
                ('deadline', models.DateTimeField()),
                ('keterangan', models.TextField(blank=True)),
                ('file_tugas', models.FileField(upload_to='tugas_files/')),
                ('jurusan', models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Farmasi', 'Farmasi')], max_length=50)),
                ('semester', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4'), ('semester5', 'Semester 5'), ('semester6', 'Semester 6'), ('semester7', 'Semester 7'), ('semester8', 'Semester 8')], max_length=20)),
                ('nama_pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10)),
                ('waktu', models.CharField(max_length=20)),
                ('kode_mata_kuliah', models.CharField(max_length=20)),
                ('nama_mata_kuliah', models.CharField(max_length=100)),
                ('sks', models.IntegerField()),
                ('jurusan', models.CharField(choices=[('Teknik Informatika', 'Teknik Informatika'), ('Teknik Elektro', 'Teknik Elektro'), ('Farmasi', 'Farmasi')], max_length=50)),
                ('semester', models.CharField(choices=[('semester1', 'Semester 1'), ('semester2', 'Semester 2'), ('semester3', 'Semester 3'), ('semester4', 'Semester 4'), ('semester5', 'Semester 5'), ('semester6', 'Semester 6'), ('semester7', 'Semester 7'), ('semester8', 'Semester 8')], max_length=20)),
                ('ruangan', models.CharField(max_length=50)),
                ('metode_pembelajaran', models.CharField(choices=[('luring', 'Luring'), ('daring', 'Daring')], max_length=10)),
                ('dosen', models.ForeignKey(limit_choices_to={'role': 'dosen'}, on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
    ]
