# Generated by Django 4.1 on 2023-07-01 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_jadwal_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwal',
            name='waktu_selesai',
            field=models.TimeField(default=datetime.datetime(2023, 7, 1, 14, 18, 4, 461116, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='waktu',
            field=models.TimeField(),
        ),
    ]
