# Generated by Django 4.1 on 2023-07-01 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_jadwal_waktu_selesai_alter_jadwal_hari_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('materi', 'Materi'), ('tugas', 'Tugas')], default=datetime.datetime(2023, 7, 1, 14, 38, 50, 509040, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
    ]
