# Generated by Django 4.1 on 2023-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tugas_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('tugas', 'Tugas'), ('materi', 'Materi')], max_length=50),
        ),
    ]
