# Generated by Django 4.1 on 2023-07-02 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_remove_tugas_pengirim_tugas_alter_tugas_jenis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TampungTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kirim', models.DateTimeField(auto_now_add=True)),
                ('file_tugas', models.FileField(upload_to='tugas_files/')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tugas')),
            ],
        ),
    ]
