# Generated by Django 4.1 on 2023-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_tampungtugas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='metode_pembelajaran',
            field=models.CharField(choices=[('Luring', 'Luring'), ('Daring', 'Daring')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('tugas', 'Tugas'), ('materi', 'Materi')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.CharField(choices=[('Semester1', 'Semester 1'), ('Semester2', 'Semester 2'), ('Semester3', 'Semester 3'), ('Semester4', 'Semester 4'), ('Semester5', 'Semester 5'), ('Semester6', 'Semester 6'), ('Semester7', 'Semester 7'), ('Semester8', 'Semester 8')], max_length=20),
        ),
    ]
